### ISSUE TITLE
Choose network API interface library

### ISSUE THREAD

**Issue by LukeAngove** [LukeAngove/cpp_rpg#4]
We want to some kind of network API to have people interact with our service. We need to choose one.
Options include:

- REST
- gRPC
- GraphQL
- Something else that's better for some reason

We need to choose one and add it to the Bazel build using the WORKSPACE file.
Include a simple API that returns 'true' and a test for it.

**Comment by Johjahn1** [comment]
We will use gRPC, I do not know how to implement it.
